application: icondb
version: 1
runtime: python27
api_version: 1
threadsafe: yes
default_expiration: "1d"

handlers:
- url: /api/.*
  script: main.app

- url: /static
  static_dir: static

- url: /
  static_files: static/index.html
  upload: static/index\.html

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico


libraries:
- name: webapp2
  version: "2.5.1"
